version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo-local
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db

  ai:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-local
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGODB_URL=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/${MONGO_DB_NAME}?authSource=admin
    volumes:
      - .:/app
      - C:/service-account.json:/app/service-account.json
    restart: unless-stopped

volumes:
  mongo-data:
