version: "3.8"

services:
  ai:
    image: zezeonekesb/ai:latest
    container_name: ai
    restart: always
    ports:
      - "8000:8000"
    environment:
      MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/${MONGO_DB_NAME}?authSource=admin
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    external: true
    name: backend_app-network
